### ISSUE TITLE
Use `knitr` by default for compiling `README.Rmd`?

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/recontools#11]
Currently it looks like the template supposes `rmarkdown`. I personally prefer to use `knit()`, but I may be missing some reason why  `rmarkdown` should be preferred. If so, I would add `README.html` to `.gitignore` as it will be produced when calling `rmarkdown`.

**Comment by dirkschumacher** [comment]
I think this is now setup that way.

**Comment by dirkschumacher** [comment]
`rmarkdown` is needed for `devtools::use_vignette`. This is just temporary as we would like to use our own template for vignettes anyways
